'use client';

import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Project = { id: string; name: string; slug: string };
type Profile = { id: string; email: string; full_name: string | null };
const roles = [
  ['owner', 'Owner · dirige cliente y decisiones'], ['creator', 'Creativa · propone ideas y briefs'], ['camera', 'Cámara · rodaje y crudo'], ['model', 'Modelo · ejecución de talento'], ['editor', 'Editor · versiones y cortes'], ['publisher', 'Publisher · salidas y evidencia'], ['media_buyer', 'Pauta · objetivos y resultados'], ['client_approver', 'Cliente · aprueba ideas y guiones'], ['client_viewer', 'Cliente · consulta sin editar'],
];

export function AccessAdmin() {
  const supabase = useMemo(() => createClient(), []);
  const [projects, setProjects] = useState<Project[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]);
  const [email, setEmail] = useState(''); const [projectId, setProjectId] = useState(''); const [role, setRole] = useState('creator'); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(() => Boolean(supabase));
  useEffect(() => { if (!supabase) return; void (async () => { const [{ data: projectRows }, { data: profileRows }] = await Promise.all([supabase.from('projects').select('id,name,slug').order('name'), supabase.from('profiles').select('id,email,full_name').order('email')]); setProjects(projectRows ?? []); setProfiles(profileRows ?? []); setProjectId(projectRows?.[0]?.id ?? ''); setLoading(false); })(); }, [supabase]);
  const grant = async (event: React.FormEvent) => { event.preventDefault(); if (!supabase) { setNotice('Supabase aún no está configurado. Consulta AUTH_SETUP.md antes de activar accesos.'); return; } const profile = profiles.find((item) => item.email.toLowerCase() === email.trim().toLowerCase()); if (!profile || !projectId) { setNotice('No encontramos ese correo. La persona debe iniciar sesión con Google una vez antes de recibir acceso.'); return; } const { error } = await supabase.from('user_project_access').upsert({ user_id: profile.id, project_id: projectId, role_in_project: role }, { onConflict: 'user_id,project_id' }); setNotice(error ? `No fue posible asignar acceso: ${error.message}` : `✓ Acceso asignado a ${profile.email}. Al entrar verá solamente este proyecto y su cola.`); };
  return <section className="border-2 border-blanco p-6 sm:p-8"><p className="eyebrow">[ADMINISTRACIÓN DE ACCESOS]</p><h2 className="mt-3 font-display text-4xl font-bold text-blanco">EQUIPO Y<br/><span className="text-mostaza">PROYECTOS.</span></h2><p className="mt-4 max-w-2xl text-sm leading-7 text-blanco-60">Asigna una persona a un proyecto y define su relevo operativo. El permiso se aplica al iniciar sesión; no se comparte información entre clientes.</p>{!supabase && <p role="status" className="mt-6 border-2 border-orquidea bg-orquidea/10 p-4 font-mono text-xs leading-6 text-blanco">[CONFIGURACIÓN PENDIENTE] El panel estará activo al conectar la clave pública de Supabase y aplicar la migración de roles.</p>}{loading ? <p className="mt-8 font-mono text-xs text-blanco-60">CARGANDO PROYECTOS Y PERFILES…</p> : <form onSubmit={grant} className="mt-8 grid gap-5 border-t border-blanco-20 pt-7 lg:grid-cols-2"><label><span className="mono-label mb-2 block text-mostaza">// CORREO DE GOOGLE</span><input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="input-brutal" placeholder="persona@gmail.com" /></label><label><span className="mono-label mb-2 block text-mostaza">// PROYECTO</span><select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="input-brutal">{projects.length ? projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>) : <option value="">Sin proyectos cargados</option>}</select></label><label className="lg:col-span-2"><span className="mono-label mb-2 block text-mostaza">// ROL EN ESTE PROYECTO</span><select value={role} onChange={(event) => setRole(event.target.value)} className="input-brutal">{roles.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="lg:col-span-2 flex flex-col gap-4 sm:flex-row sm:items-center"><button disabled={!supabase} className="btn-brutal" type="submit">ASIGNAR ACCESO →</button><span className="font-mono text-[10px] leading-5 text-blanco-40">La persona debe haber iniciado sesión una vez para que aparezca su perfil.</span></div>{notice && <p role="status" className="lg:col-span-2 border border-mostaza bg-mostaza/10 p-4 font-mono text-xs leading-6 text-blanco">{notice}</p>}</form>}</section>;
}
