'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

type FormState = { title: string; type: string; category: string; objective: string; description: string; camera: string; talent: string; edit: string; reference: string };
const empty: FormState = { title: '', type: 'Orgánico', category: '', objective: '', description: '', camera: '', talent: '', edit: '', reference: '' };

export function NewIdeaForm({ projectSlug }: { projectSlug: string }) {
  const router = useRouter(); const key = `rr-draft-${projectSlug}`; const [form, setForm] = useState<FormState>(empty); const [saved, setSaved] = useState(false);
  useEffect(() => { const timer = window.setTimeout(() => { const draft = localStorage.getItem(key); if (draft) setForm(JSON.parse(draft)); }, 0); return () => window.clearTimeout(timer); }, [key]);
  useEffect(() => { localStorage.setItem(key, JSON.stringify(form)); }, [key, form]);
  function update(field: keyof FormState, value: string) { setSaved(false); setForm(current => ({ ...current, [field]: value })); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!form.title.trim()) return; setSaved(true); }
  return <form onSubmit={submit} className="mt-10 space-y-6"><Field label="TÍTULO" value={form.title} onChange={value => update('title', value)} placeholder="Ej. La textura que se siente"/><div className="grid gap-6 md:grid-cols-2"><Field label="TIPO" value={form.type} onChange={value => update('type', value)} select options={['Orgánico','Pauta']}/><Field label="CATEGORÍA" value={form.category} onChange={value => update('category', value)} placeholder="Producto y tela"/></div><Field label="OBJETIVO" value={form.objective} onChange={value => update('objective', value)} textarea placeholder="¿Qué debe conseguir esta pieza?"/><Field label="DESCRIPCIÓN / CONCEPTO" value={form.description} onChange={value => update('description', value)} textarea placeholder="Describe la idea en lenguaje claro..."/><Field label="REFERENCIA VISUAL (URL DE INSTAGRAM)" value={form.reference} onChange={value => update('reference', value)} placeholder="https://www.instagram.com/reel/..."/><div className="grid gap-6 md:grid-cols-3"><Field label="CÁMARA" value={form.camera} onChange={value => update('camera', value)} textarea placeholder="Especificaciones"/><Field label="TALENTO" value={form.talent} onChange={value => update('talent', value)} textarea placeholder="Modelo / perfil"/><Field label="EDICIÓN" value={form.edit} onChange={value => update('edit', value)} textarea placeholder="Ritmo / audio"/></div><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><button className="btn-brutal" type="submit">{saved ? 'BORRADOR GUARDADO ✓' : 'GUARDAR BORRADOR →'}</button>{saved && <button type="button" onClick={() => router.push(`/${projectSlug}/ideas`)} className="font-mono text-xs text-mostaza underline">VOLVER AL BANCO</button>}</div><p className="font-mono text-[10px] text-blanco-40">AUTOGUARDADO LOCAL ACTIVO · AL CONECTAR SUPABASE SE SINCRONIZA CON EL EQUIPO.</p></form>;
}
function Field({ label, value, onChange, placeholder, textarea, select, options }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; textarea?: boolean; select?: boolean; options?: string[] }) { return <label className="block"><span className="mono-label mb-2 block text-mostaza">// {label}</span>{select ? <select value={value} onChange={event => onChange(event.target.value)} className="input-brutal">{options?.map(option => <option key={option}>{option}</option>)}</select> : textarea ? <textarea value={value} onChange={event => onChange(event.target.value)} className="input-brutal min-h-28" placeholder={placeholder}/> : <input value={value} onChange={event => onChange(event.target.value)} className="input-brutal" placeholder={placeholder}/>}</label>; }
