'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { ReferenceEmbed } from '@/components/reference-embed';
import { createClient } from '@/lib/supabase/client';

type FormState = { title: string; type: 'Orgánico' | 'Pauta'; category: string; objective: string; description: string; camera: string; talent: string; edit: string; reference: string };
const empty: FormState = { title: '', type: 'Orgánico', category: '', objective: '', description: '', camera: '', talent: '', edit: '', reference: '' };

export function NewIdeaForm({ projectSlug }: { projectSlug: string }) {
  const router = useRouter(); const supabase = useMemo(() => createClient(), []); const [form, setForm] = useState<FormState>(empty); const [notice, setNotice] = useState(''); const [saving, setSaving] = useState(false);
  const update = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }));
  async function submit(event: React.FormEvent) {
    event.preventDefault();
    if (!form.title.trim() || !form.objective.trim()) { setNotice('Completa al menos título y objetivo para conservar el contexto de la idea.'); return; }
    if (!supabase) { setNotice('Supabase no está configurado en este entorno. Avisa al administrador para activar el guardado compartido.'); return; }
    setSaving(true);
    const { data: project, error: projectError } = await supabase.from('rr_hub_projects').select('id').eq('slug', projectSlug).maybeSingle();
    if (projectError || !project) { setNotice('No pudimos encontrar el proyecto autorizado. Vuelve a iniciar sesión o contacta al administrador.'); setSaving(false); return; }
    const { data, error } = await supabase.from('rr_hub_ideas').insert({ project_id: project.id, title: form.title.trim(), description: form.description.trim() || 'Sin descripción aún.', objective: form.objective.trim(), content_type: form.type === 'Orgánico' ? 'organic' : 'paid', category: form.category.trim() || 'Sin categoría', status: 'draft', priority: 'normal', camera_brief: form.camera.trim() || 'Pendiente de definir', talent_brief: form.talent.trim() || 'Pendiente de definir', edit_brief: form.edit.trim() || 'Pendiente de definir', reference_urls: form.reference.trim() ? [form.reference.trim()] : [] }).select('id').single();
    if (error || !data) { setNotice(`No se guardó la idea: ${error?.message ?? 'error desconocido'}.`); setSaving(false); return; }
    router.push(`/${projectSlug}/ideas/${data.id}`);
  }
  return <form onSubmit={submit} className="mt-10 space-y-6"><div className="border-l-2 border-orquidea bg-orquidea/10 px-4 py-3 font-mono text-[10px] leading-5 text-blanco-60">[CAPTURA GUIADA] Primero registra la intención. Los responsables completan el brief técnico después de que la idea avance.</div>{notice && <p role="alert" className="border-2 border-fucsia bg-fucsia/10 p-3 font-mono text-xs text-blanco">{notice}</p>}<Field label="TÍTULO *" value={form.title} onChange={(value) => update('title', value)} placeholder="Ej. La textura que se siente"/><div className="grid gap-6 md:grid-cols-2"><Field label="TIPO" value={form.type} onChange={(value) => update('type', value)} select options={['Orgánico','Pauta']}/><Field label="CATEGORÍA" value={form.category} onChange={(value) => update('category', value)} placeholder="Producto y tela"/></div><Field label="OBJETIVO *" value={form.objective} onChange={(value) => update('objective', value)} textarea placeholder="¿Qué debe conseguir esta pieza?"/><Field label="DESCRIPCIÓN / CONCEPTO" value={form.description} onChange={(value) => update('description', value)} textarea placeholder="Describe la idea en lenguaje claro para el cliente y el equipo..."/><Field label="REFERENCIA VISUAL (INSTAGRAM, TIKTOK, YOUTUBE O FACEBOOK)" value={form.reference} onChange={(value) => update('reference', value)} placeholder="Pega un enlace: la previsualización aparece abajo"/>{form.reference.trim() && <section aria-live="polite"><p className="mono-label mb-2 text-mostaza">// PREVISUALIZACIÓN AUTOMÁTICA</p><ReferenceEmbed url={form.reference.trim()} title={form.title || 'Nueva idea'} /></section>}<div className="grid gap-6 md:grid-cols-3"><Field label="CÁMARA" value={form.camera} onChange={(value) => update('camera', value)} textarea placeholder="Planos, luz, lente"/><Field label="TALENTO" value={form.talent} onChange={(value) => update('talent', value)} textarea placeholder="Vestuario, actitud"/><Field label="EDICIÓN" value={form.edit} onChange={(value) => update('edit', value)} textarea placeholder="Ritmo, textos, audio"/></div><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><button disabled={saving} className="btn-brutal" type="submit">{saving ? 'GUARDANDO…' : 'CREAR IDEA →'}</button><span className="font-mono text-[10px] text-blanco-40">{supabase ? 'SE GUARDARÁ EN EL PROYECTO COMPARTIDO' : 'GUARDADO COMPARTIDO NO DISPONIBLE'}</span></div></form>;
}
function Field({ label, value, onChange, placeholder, textarea, select, options }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; textarea?: boolean; select?: boolean; options?: string[] }) { return <label className="block"><span className="mono-label mb-2 block text-mostaza">// {label}</span>{select ? <select value={value} onChange={(event) => onChange(event.target.value)} className="input-brutal">{options?.map((option) => <option key={option}>{option}</option>)}</select> : textarea ? <textarea value={value} onChange={(event) => onChange(event.target.value)} className="input-brutal min-h-28" placeholder={placeholder}/> : <input value={value} onChange={(event) => onChange(event.target.value)} className="input-brutal" placeholder={placeholder}/>}</label>; }
