import Link from 'next/link';

function instagramEmbed(url: string) { const clean = url.split('?')[0].replace(/\/$/, ''); return `${clean}/embed/captioned/`; }
function youtubeEmbed(url: string) { const match = url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{6,})/); return match ? `https://www.youtube.com/embed/${match[1]}` : null; }
function tiktokEmbed(url: string) { const match = url.match(/video\/(\d+)/); return match ? `https://www.tiktok.com/embed/v2/${match[1]}` : null; }

export function ReferenceEmbed({ url, title }: { url?: string; title: string }) {
  if (!url) return <div className="grid min-h-64 place-items-center border-2 border-dashed border-blanco-20 p-8 text-center"><div><p className="mono-label text-mostaza">[REFERENCIA PENDIENTE]</p><p className="mt-3 text-sm leading-6 text-blanco-60">Esta idea no tiene un referente visual todavía. El owner debe agregarlo antes de enviarla al cliente.</p></div></div>;
  const source = url.includes('instagram.com') ? instagramEmbed(url) : url.includes('youtube.com') || url.includes('youtu.be') ? youtubeEmbed(url) : url.includes('tiktok.com') ? tiktokEmbed(url) : url.includes('facebook.com') ? `https://www.facebook.com/plugins/post.php?href=${encodeURIComponent(url)}&show_text=false&width=500` : null;
  return <div className="overflow-hidden border-2 border-blanco bg-black"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-blanco-20 px-3 py-3 sm:px-4"><span className="mono-label text-mostaza">[VISUAL_REFERENCE · {url.includes('instagram') ? 'INSTAGRAM' : url.includes('facebook') ? 'FACEBOOK' : url.includes('tiktok') ? 'TIKTOK' : url.includes('youtube') || url.includes('youtu.be') ? 'YOUTUBE' : 'EXTERNA'}]</span><Link href={url} target="_blank" rel="noreferrer" className="font-mono text-[10px] text-fucsia">ABRIR ORIGINAL ↗</Link></div>{source ? <iframe title={`Referencia visual de ${title}`} src={source} className="h-[390px] w-full bg-white sm:h-[520px]" allow="autoplay; clipboard-write; encrypted-media; picture-in-picture; web-share"/> : <div className="grid min-h-64 place-items-center p-8 text-center"><div><p className="font-mono text-xs text-blanco-60">PREVIEW NO DISPONIBLE PARA ESTE ORIGEN.</p><Link href={url} target="_blank" rel="noreferrer" className="mt-4 inline-block font-mono text-xs text-mostaza underline">VER REFERENCIA ORIGINAL ↗</Link></div></div>}</div>;
}
