'use client';
import { useState } from 'react';
const roles: Record<string, { title: string; copy: string; bullets: string[] }> = {
  CLIENTE: { title: 'DECISIÓN Y CONTEXTO', copy: 'Revisa la intención, la referencia y lo que necesitamos confirmar antes de producir.', bullets: ['Aprobar o solicitar ajustes', 'Confirmar prendas y restricciones', 'Dejar una decisión visible'] },
  MODELO: { title: 'EJECUCIÓN DE TALENTO', copy: 'Guía rápida para saber qué hacer frente a cámara y mantener consistencia.', bullets: ['Movimiento y actitud', 'Vestuario y continuidad', 'Notas del director'] },
  CÁMARA: { title: 'PLAN DE RODAJE', copy: 'Información técnica para convertir el concepto en tomas ejecutables.', bullets: ['Planos, lente y foco', 'Luz y encuadre', 'Checklist de captura'] },
  EDITOR: { title: 'CONSTRUCCIÓN DE LA PIEZA', copy: 'Mapa para editar con intención y entregar versiones comparables.', bullets: ['Duración y ritmo', 'Textos, audio y formatos', 'Subir V1 y V2'] },
  PAUTA: { title: 'RESULTADO COMERCIAL', copy: 'La pieza vista desde objetivo, audiencia, CTA y aprendizaje.', bullets: ['Objetivo de conversión', 'Variantes de copy', 'Métricas e iteración'] },
};
export function RoleView() { const [role, setRole] = useState('CLIENTE'); const content = roles[role]; return <div className="brutal-panel"><p className="mono-label text-mostaza">// VISTA OPERATIVA</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{Object.keys(roles).map(item => <button type="button" key={item} onClick={() => setRole(item)} aria-pressed={role === item} className={`border px-2 py-3 text-left font-mono text-[10px] ${role === item ? 'border-fucsia bg-fucsia/10 text-blanco' : 'border-blanco-20 text-blanco-60 hover:border-mostaza hover:text-mostaza'}`}>{item}</button>)}</div><div className="mt-6 border-t border-blanco-20 pt-5"><p className="eyebrow">[ROLE: {role}]</p><h3 className="mt-2 font-display text-2xl font-bold text-blanco">{content.title}</h3><p className="mt-3 text-sm leading-6 text-blanco-60">{content.copy}</p><ul className="mt-4 space-y-2 font-mono text-[11px] text-mostaza">{content.bullets.map(bullet => <li key={bullet}>→ {bullet}</li>)}</ul></div></div>; }
