'use client';
import Link from 'next/link';
import { useParams, usePathname } from 'next/navigation';
import { useState } from 'react';

const modes = [
  ['Resumen', ''], ['Ideas', '/ideas'], ['Producción', '/produccion'], ['Aprobaciones', '/aprobaciones'], ['Publicaciones', '/publicaciones'], ['Métricas', '/metricas'],
];

export function WorkspaceShell({ children, project, role }: { children: React.ReactNode; project: any; role: string }) {
  const params = useParams<{ projectSlug: string }>(); const pathname = usePathname(); const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen bg-negro md:flex"><aside className={`fixed inset-y-0 left-0 z-40 w-72 border-r-2 border-blanco bg-negro p-5 transition-transform md:static md:translate-x-0 ${menuOpen ? 'translate-x-0' : '-translate-x-full'}`}><div className="mb-10 flex items-center justify-between"><Link href="/select-project" className="flex items-center gap-3"><img src="/brand/rr-brandmark.png" alt="RR Aliados" className="h-9 w-28 object-cover object-left-top"/><span className="sr-only">Cambiar proyecto</span></Link><button onClick={()=>setMenuOpen(false)} className="font-mono text-xs text-blanco-60 md:hidden">×</button></div><div className="border-b border-blanco-10 pb-6"><p className="mono-label text-mostaza">PROYECTO ACTIVO</p><Link href={`/${project.slug}`} className="mt-2 block font-display text-2xl font-bold text-blanco hover:text-fucsia">{project.name}</Link><p className="mt-1 font-mono text-[10px] text-blanco-40">{project.client_name}</p></div><nav className="mt-6 space-y-1" aria-label="Navegación del proyecto">{modes.map(([label, path])=>{const href=`/${params.projectSlug}${path}`;const active=path?pathname.startsWith(href):pathname===`/${params.projectSlug}`;return <Link key={label} href={href} onClick={()=>setMenuOpen(false)} className={`flex items-center justify-between border-l-2 px-3 py-3 font-mono text-xs ${active?'border-fucsia bg-fucsia/10 text-blanco':'border-transparent text-blanco-60 hover:border-mostaza hover:text-mostaza'}`}><span>{label.toUpperCase()}</span>{label==='Aprobaciones'&&<span className="text-mostaza">3</span>}</Link>})}</nav><div className="mt-8 border-t border-blanco-10 pt-6"><p className="mono-label text-blanco-40">VISTA ACTUAL</p><p className="mt-2 font-mono text-xs text-orquidea">[{role.toUpperCase()}]</p><button className="mt-4 font-mono text-[10px] text-mostaza underline">Cambiar vista de rol</button></div></aside><div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex items-center justify-between border-b-2 border-blanco bg-negro/95 px-5 py-4 backdrop-blur md:px-10"><button onClick={()=>setMenuOpen(true)} className="font-mono text-xs text-mostaza md:hidden">☰ MENÚ</button><span className="hidden font-mono text-[10px] text-blanco-40 md:block">RR CONTENT HUB // {project.name}</span><div className="flex items-center gap-3"><span className="h-2 w-2 bg-mostaza"/><span className="font-mono text-[10px] text-blanco-60">SISTEMA ACTIVO</span></div></header>{children}</div></div>;
}
