import Link from 'next/link';
import { StatusBadge } from './status-badge';

const guides: Record<string, { owner: string; next: string; empty: string }> = {
  PRODUCCIÓN: { owner: 'CÁMARA · TALENTO · EDITOR', next: 'Una idea solo entra aquí después de la aprobación del cliente. Cada rol abre su brief y marca el siguiente relevo.', empty: 'Aún no hay piezas aprobadas que requieran rodaje o edición.' },
  APROBACIONES: { owner: 'OWNER DEL PROYECTO · CLIENTE', next: 'Aquí se presenta la idea y el cliente decide: aprobar, pedir ajustes o rechazar. La decisión queda ligada a la pieza.', empty: 'No hay decisiones pendientes del cliente. Las nuevas ideas deben enviarse a revisión desde su ficha.' },
  PUBLICACIONES: { owner: 'PUBLISHER · MEDIA BUYER · OWNER', next: 'Aquí se programan únicamente piezas con revisión final. Registra plataforma, copy, fecha y enlace de salida.', empty: 'No hay piezas listas para publicar. WUNDEER aún no tiene contenido multimedia publicado.' },
  MÉTRICAS: { owner: 'MEDIA BUYER · OWNER DEL PROYECTO', next: 'Después de publicar se registra la hipótesis, URL y resultado para decidir qué formato se repite.', empty: 'No hay métricas todavía porque no hay publicaciones registradas.' },
};

export function WorkspaceSection({ title, eyebrow, description, ideas, projectSlug, action }: { title: string; eyebrow: string; description: string; ideas: any[]; projectSlug: string; action: string }) {
  const guide = guides[title] ?? { owner: 'RR ALIADOS', next: description, empty: 'No hay registros en esta cola.' };
  return <main className="min-h-screen bg-negro"><div className="mx-auto max-w-7xl px-5 py-10 md:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-6 border-b border-blanco-10 pb-8"><div><p className="eyebrow">{eyebrow}</p><h1 className="display-title">{title}<br/><em>EN CONTROL.</em></h1><p className="mt-5 max-w-xl text-sm leading-7 text-blanco-60">{description}</p></div><Link href={`/${projectSlug}/ideas`} className="btn-brutal">{action} →</Link></div><section className="mb-8 grid gap-px border-2 border-mostaza bg-mostaza md:grid-cols-[.75fr_1.25fr]"><div className="bg-negro p-5"><p className="mono-label text-mostaza">[QUIÉN ACTÚA]</p><p className="mt-3 font-display text-2xl font-bold text-blanco">{guide.owner}</p></div><div className="bg-negro p-5"><p className="mono-label text-mostaza">[QUÉ PASA AQUÍ]</p><p className="mt-3 text-sm leading-6 text-blanco-60">{guide.next}</p></div></section>{ideas.length ? <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{ideas.map((idea) => <Link key={idea.id} href={`/${projectSlug}/ideas/${idea.id}`} className="brutal-panel group"><div className="mb-6 flex justify-between gap-3"><span className="mono-label text-mostaza">{idea.code ?? 'ITEM'} · {idea.category}</span><StatusBadge status={idea.status}/></div><h2 className="font-display text-2xl font-bold text-blanco group-hover:text-fucsia">{idea.title}</h2><p className="mt-3 text-sm leading-6 text-blanco-60">{idea.description}</p><div className="mt-7 border-t border-blanco-10 pt-4 font-mono text-[10px] text-blanco-40">RESPONSABLE: {idea.creator ?? 'RR ALIADOS'} <span className="float-right text-fucsia">ABRIR →</span></div></Link>)}</div> : <section className="border-2 border-dashed border-blanco-20 px-6 py-16 text-center"><p className="eyebrow">[COLA VACÍA]</p><h2 className="mt-3 font-display text-3xl font-bold text-blanco">{guide.empty}</h2><Link href={`/${projectSlug}/ideas`} className="mt-6 inline-block font-mono text-xs text-mostaza underline">IR AL BANCO DE IDEAS →</Link></section>}</div></main>;
}
